In [1]:
import modin.pandas as pd
import numpy as np
import gensim
from tqdm import tqdm 
import re
import os
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from gensim.models import Word2Vec
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from gensim.similarities import WmdSimilarity
from datetime import datetime

pd.set_option('display.max_colwidth', None)

In [2]:
def preprocess_text(text):
    text = nltk.word_tokenize(text)
    text=[word.lower() for word in text if word.isalpha()]
    filtered_text = [word for word in text if word not in stopwords.words('english') and not(re.match(r"\d",word))]
    lemmatized_text = [lemmatizer.lemmatize(word) for word in filtered_text]
    return lemmatized_text

In [3]:
annotated_data_dir = "C:\\Users\\eshad\\OneDrive\\Desktop\\TU Delft\\Thesis\\Web Scrape PoC\\Data\\7. Deduplicated data\\"

In [4]:
dataframes = []
folders = ["Batch 1\\"] #, "Batch 2\\", "Batch 3\\"]
# Read all files in the directory
for folder_name in folders:
    for file_name in os.listdir(os.path.join(annotated_data_dir, folder_name)):
        if file_name.endswith('annotated_data_2024_removed_words.csv'): 
            print(file_name)
            file_path = os.path.join(annotated_data_dir, folder_name, file_name)
            tmp_df = pd.read_csv(file_path, usecols = ['jobPostingId', 'title', 'description', 'gender_category'])
            tmp_df = tmp_df.dropna(how='any')
            dataframes.append(tmp_df)
job_postings_df = pd.concat(dataframes)
print(len(job_postings_df))
job_postings_df.head()

annotated_data_2024_removed_words.csv

2025-04-09 13:39:50,545	INFO worker.py:1841 -- Started a local Ray instance.
UserWarning: `read_*` implementation has mismatches with pandas:
Data types of partitions are different! Please refer to the troubleshooting section of the Modin documentation to fix this issue.

40834

   jobPostingId                                     title  \
0    3824426275               Retail Front End Supervisor
1    3824425537                   DevOps Engineer, Senior
2    3824425417               Retail Front End Supervisor
3    3824425039  Risk & Abuse Operations and Data Analyst
4    3824424451               Retail Front End Supervisor

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  description  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   LOCATION 8141 Sawyer Brown Rd Nashville TN US 37221\n\nOverview\n\nAt Burlington, we embrace the many facets of diversity that strengthen our communities where we live and work every day. If you want to grow your retail career with a caring and inclusive organization, come join us as a Burlington Stores Full-Time Customer Service Supervisor or Full-Time Selling Floor Supervisor!\n\nAs a Retail Front End Supervisor, you’ll be an integral part of the store leadership team, working closely with Store Management in the areas of Merchandising, Customer Service, Operations, and Human Resources. This leadership position is the stepping-stone to a management role within our expanding organization. Are you a self-starter with the ability to supervise store operations efficiently and effectively? If you are a proven leader who understands the value of building strong teams and partnerships to drive results, this is the right opportunity for you!\n\nAt Burlington, we live by our Core Values:\n\nDrive ResultsTrust & Respect Each OtherBuild Teams & Partnerships\n\nBurlington Benefits:\n\nGrowth OpportunitiesCompetitive PayFlexible Hours15-30% Associate DiscountMedical, Dental, and Vision CoverageEmployee Assistance ProgramLife and Disability InsurancePaid Time OffPaid Holidays401 (k)\n\nKey Responsibilities:\n\nSupervise all store functions and associates while in the role of Manager on DutyMaximize sales results through training, developing, and coaching of direct reportsPromote safety for both our customers and associates by adhering to company guidelinesCultivate a diverse culture based on teamwork and collaborationSolve issues/concerns, making informed decisions and supervising the front-end operations to ensure all Burlington customers are provided with exceptional, friendly, and professional customer service at all timesReinforce our company Asset Protection strategies to eliminate shortageAssist in recruiting, interviewing, and onboarding new associatesParticipate in weekly workload planning meetingsDrives Community Relations participation through company programs and partnershipsCoordinate meal and break periods and monitors schedule adherence\n\nRequirements:\n\nAt least 1 year of supervisory experience within an off-price, big box or a specialty environmentStrong interpersonal skills with a positive and engaging attitudeAbility to work a full-time schedule including nights, weekends and holidays as requiredAbility to move/handle/lift store merchandise weighing 40 lbs. or more, as well as the ability to stand and walk for extended periods of time\n\nAt Burlington we’re opening more stores nationwide to provide you with even more locations to enjoy our amazing prices on the brands and styles you love. As we grow, you can too through a variety of training and development opportunities!\n\nCome join our team. You’re going to like it here!\n\nYou will enjoy a competitive wage, flexible hours, and an associate discount. Burlington's benefits package includes medical, dental, and vision coverage including life and disability insurance. Full time associates may also be eligible for up to 12 days of paid time off annually, up to 8 paid holidays, paid sick time in accordance with applicable law, and a 401(k) plan. We are a rapidly growing brand and provide a variety of training and development opportunities so our associates can grow with us.\n\nOur store teams work hard and have fun together! Burlington associates make a difference in the lives of customers, colleagues, and the communities where we live and work every day. Burlington Stores, Inc. is an equal opportunity employer committed to workplace diversity.\n\nLocation US-TN-Nashville\n\nPosting Number 2024-214808\n\nAddress 8141 Sawyer Brown Rd\n\nZip Code 37221\n\nWorkplace Type On-Site\n\nPosition Type Regular Full-Time\n\nCareer Site Category Store Associate\n\nPosition Category Store Supervisor\n\nEvergreen Yes\n\nMin USD $13.00/Hour\n\nMid USD $15.00/Hour
1  Job Number: R0190517\n\nDevOps Engineer, Senior\n\nThe Opportunity:\n\nAs a DevOps engineer, you know how to set up cloud environments and provision computer networking, storage, and virtual networks—ultimately, how to “harness the cloud”. We’re looking for an experienced DevOps infrastructure engineer like you to support our clients as they modernize their IT infrastructures and meet their most challenging missions.\n\nAs a DevOps infrastructure engineer at Booz Allen, you’ll work closely with cloud architects and engineers to manage server configuration for modern cloud solutions. You’ll apply your skills within a DevOps framework to establish or provision virtual machines or networks and use cloud service providers to further your clients’ meaningful missions.\n\nWith access to our internal innovative labs, there’s no better place to further your skills and explore different ways of solving our clients’ challenges. Whether helping to develop, deploy, or manage IT infrastructures for crucial server and network components, here you’ll have the latest tech and brightest teammates at your fingertips.\n\nJoin us. The world can’t wait.\n\nYou Have:\n\nExperience in the development of tools and processes to drive DevOps or DevSecOps maturity by automating builds, regression testing, monitoring, and pushing releases across environmentsExperience troubleshooting, triaging, and resolving issues related to CI/CD pipeline failures or slownessExperience writing scripts using tools such as Python, Bash, or Boto3Experience with Infrastructure-as-Code using Ansible and deploying apps on RancherExperience developing enterprise cloud-native solutions, including S3 Bucket integrationExperience creating solutions to complex problems within a collaborative team environmentTS/SCI clearance with a polygraphBachelor’s degree or 6+ years of experience in DevOps in lieu of a degree \n\n\nNice If You Have:\n\nExperience developing enterprise cloud-native solutions with Kubernetes, Docker, AWS, Jenkins, Terraform, or AzureExperience with Apache NiFi flow engineeringExperience with Gitlab CI/CD pipelineBachelor's degree in engineering, CS, or Technology\n\n\nClearance: \n\nApplicants selected will be subject to a security investigation and may need to meet eligibility requirements for access to classified information; TS/SCI clearance with polygraph is required.\n\nCreate Your Career: \n\nGrow With Us\n\nYour growth matters to us—that’s why we offer a variety of ways for you to develop your career. With professional and leadership development opportunities like upskilling programs, tuition reimbursement, mentoring, and firm-sponsored networking, you can chart a unique and fulfilling career path on your own terms.\n\nA Place Where You Belong\n\nDiverse perspectives cultivate collective ingenuity. Booz Allen’s culture of respect, equity, and opportunity means that, here, you are free to bring your whole self to work. With an array of business resource groups and other opportunities for connection, you’ll develop your community in no time.\n\nSupport Your Well-Being\n\nOur comprehensive benefits package includes wellness programs with HSA contributions, paid holidays, paid parental leave, a generous 401(k) match, and more. With these benefits, plus the option for flexible schedules and remote and hybrid locations, we’ll support you as you pursue a balanced, fulfilling life—at work and at home.\n\nYour Candidate Journey\n\nAt Booz Allen, we know our people are what propel us forward, and we value relationships most of all. Here, we’ve compiled a list of resources so you’ll know what to expect as we forge a connection with you during your journey as a candidate with us.\n\nCompensation\n\nAt Booz Allen, we celebrate your contributions, provide you with opportunities and choices, and support your total well-being. Our offerings include health, life, disability, financial, and retirement benefits, as well as paid leave, professional development, tuition assistance, work-life programs, and dependent care. Our recognition awards program acknowledges employees for exceptional performance and superior demonstration of our values. Full-time and part-time employees working at least 20 hours a week on a regular basis are eligible to participate in Booz Allen’s benefit programs. Individuals that do not meet the threshold are only eligible for select offerings, not inclusive of health benefits. We encourage you to learn more about our total benefits by visiting the Resource page on our Careers site and reviewing Our Employee Benefits page.\n\nSalary at Booz Allen is determined by various factors, including but not limited to location, the individual’s particular combination of education, knowledge, skills, competencies, and experience, as well as contract-specific affordability and organizational requirements. The projected compensation range for this position is $75,600.00 to $172,000.00 (annualized USD). The estimate displayed represents the typical salary range for this position and is just one component of Booz Allen’s total compensation package for employees. This posting will close within 90 days from the Posting Date.\n\nWork Model\n\nOur people-first culture prioritizes the benefits of flexibility and collaboration, whether that happens in person or remotely.\n\nIf this position is listed as remote or hybrid, you’ll periodically work from a Booz Allen or client site facility.If this position is listed as onsite, you’ll work with colleagues and clients in person, as needed for the specific role.\n\n\nEEO Commitment\n\nWe’re an equal employment opportunity/affirmative action employer that empowers our people to fearlessly drive change – no matter their race, color, ethnicity, religion, sex (including pregnancy, childbirth, lactation, or related medical conditions), national origin, ancestry, age, marital status, sexual orientation, gender identity and expression, disability, veteran status, military or uniformed service member status, genetic information, or any other status protected by applicable federal, state, local, or international law.

In [5]:
# # Load preprocessed datasets
# female_cvs_path = "User Data/female CVs/"
# female_cvs = []
# for file_name in os.listdir(female_cvs_path):
#     tmp_df = pd.read_csv(os.path.join(female_cvs_path, file_name)) 
#     female_cvs.append(tmp_df)
# female_cvs = pd.concat(female_cvs)
# female_cvs = female_cvs.head(25000).rename(columns = {'0': 'CV'})
# female_cvs['gender'] = 'female'
# print(len(female_cvs))
# female_cvs.head()

25000

,CV,gender
0,"```plaintext\n**Summary** \nDynamic and detail-oriented software engineer with 12-14 years of progressive experience in developing robust applications using a variety of programming languages including TypeScript, SQL, and Java. Proven expertise in leveraging web and database technologies such as Node.js, ASP.NET Core, Firebase, and MongoDB. Highly adept in employing modern frameworks and tools to streamline development processes and enhance application performance. Committed to delivering innovative solutions and continuous improvement in the software development lifecycle.\n\n**Skills** \n- **Programming Languages:** TypeScript, SQL, Java \n- **Databases:** Firebase, MongoDB \n- **Web Frameworks:** Node.js, ASP.NET Core \n- **Other Frameworks:** .NET, Keras \n- **Tools:** Git, Ansible \n- **IDEs:** Sublime Text, IntelliJ \n- **Operating Systems:** Windows, macOS \n\n**Experience** \n- Developed and maintained complex software applications, leading projects from conception through deployment. \n- Collaborated with cross-functional teams to design and implement scalable solutions, enhancing user experience and operational efficiency. \n- Utilized TypeScript and SQL for backend services and database management, demonstrating fluency in data-driven application development. \n- Leveraged frameworks such as Node.js and ASP.NET Core to build responsive web applications, driving increased engagement and usability. \n- Implemented CI/CD practices using Git and Ansible, resulting in improved deployment times and reduced rollout errors. \n\n**Education** \nBachelor’s Degree in Computer Science \n[Your University Name] \n[Year of Graduation] \nBrazil \n```",female
1,"```plaintext\n**Summary:**\nDynamic and results-driven software engineer with over 15 years of comprehensive experience in developing and implementing scalable web applications. Proficient in a diverse range of programming languages and technologies, with a strong focus on delivering efficient solutions. Seeking to leverage extensive knowledge in modern frameworks and database management in a challenging role within an innovative team.\n\n**Skills:**\n- **Programming Languages:** C#, SQL, JavaScript\n- **Databases:** MongoDB, MySQL\n- **Web Frameworks:** Angular, React.js\n- **Other Frameworks:** NumPy, .NET\n- **Tools:** Docker, Vagrant\n- **IDEs:** Visual Studio, Atom\n- **Operating Systems:** macOS, Windows\n\n**Experience:**\n- Over 15 years of professional experience in software development and project management.\n- Proven track record of successfully delivering full-stack applications using Angular and React.js integrated with both MongoDB and MySQL databases.\n- Collaborated with cross-functional teams to enhance user experience and optimize application performance.\n- Expertise in leveraging containerization and virtualization tools such as Docker and Vagrant to streamline development processes.\n\n**Education:**\n- Bachelor’s Degree in Computer Science (or relevant field)\n```",female
2,"```plaintext\n**Summary** \nDedicated and skilled female software developer with 6-8 years of comprehensive experience in designing and implementing innovative solutions. Proficient in leveraging a diverse range of programming languages and frameworks to enhance web applications and data management. Adept at collaborating in dynamic environments, driving project success through solid technical expertise, and a passion for progressing in the tech industry.\n\n**Skills** \n- **Programming Languages:** SQL, HTML/CSS, PHP \n- **Databases:** Firebase, PostgreSQL \n- **Web Frameworks:** Django, ASP.NET Core \n- **Other Frameworks:** React Native, Pandas \n- **Other Tools:** Kubernetes, Webpack \n- **IDEs:** Visual Studio Code, IntelliJ \n- **Operating Systems:** macOS, Linux \n\n**Experience** \n- Developed and maintained dynamic web applications, utilizing Django and ASP.NET Core for back-end development, ensuring optimal performance and user engagement.\n- Architected and managed databases using PostgreSQL and Firebase, enhancing data integrity and retrieval processes.\n- Implemented responsive front-end solutions using HTML/CSS and React Native, improving the user experience across various devices.\n- Collaborated with cross-functional teams to deploy applications via Kubernetes, streamlining the deployment process and enhancing scalability.\n\n**Education** \nBachelor’s Degree in Computer Science (or relevant field) \n[Your University Name] | [Graduation Year] | United States \n```",female
3,"```markdown\n**Summary** \nDynamic and detail-oriented software developer with a Bachelor’s degree and 1-2 years of experience in building robust web applications. Proficient in various programming languages and frameworks, with a strong focus on efficient code and user experience. Demonstrates excellent problem-solving skills and the ability to work collaboratively in diverse team environments, bringing a proactive approach to development and deployment processes.\n\n**Skills** \n- **Programming Languages:** TypeScript, Java, JavaScript \n- **Databases:** Firebase, MariaDB \n- **Web Frameworks:** React.js, Node.js \n- **Other Frameworks:** React Native, .NET \n- **Tools:** Docker, Ansible \n- **IDEs:** Visual Studio Code, Visual Studio \n- **Operating Systems:** Windows, Linux \n\n**Experience** \n*Software Developer* \n[Your Company Name] — Poland \n[Month, Year] to Present \n- Developed and maintained applications utilizing React.js and Node.js, enhancing user interaction and experience. \n- Collaborated with cross-functional teams to design and implement responsive web solutions, ensuring seamless integration with back-end services. \n- Worked extensively with databases like Firebase and MariaDB, optimizing data storage and retrieval processes. \n- Engaged in continuous learning and adoption of best practices in software development, contributing to team knowledge and resourcefulness.\n\n**Education** \n*Bachelor’s Degree in [Your Major]* \n[Your University Name] — [Year of Graduation] \n- Completed foundational coursework in computer science, focusing on software development methodologies and modern programming techniques. \n- Participated in various team projects that reinforced collaborative skills and practical application of theoretical knowledge.\n```",female
4,"```plaintext\n**Summary** \nDynamic and detail-oriented software developer with a Master’s degree and over three years of experience in software development. Proficient in multiple programming languages including Java, JavaScript, and C#. Demonstrates a strong ability to design and build efficient applications using a variety of frameworks and tools, while delivering high-quality code. Based in France, ready to leverage expertise in development and database management to drive innovative solutions.\n\n**Skills** \n- **Programming Languages**: Java, JavaScript, C# \n- **Databases**: MySQL, Redis \n- **Web Frameworks**: Angular, Django \n- **Other Frameworks**: NumPy, .NET \n- **Other Tools**: Ansible, Chef \n- **IDEs**: Visual Studio Code, IntelliJ \n- **Operating Systems**: Windows, Linux \n\n**Experience** \n- **Software Developer** (3-5 years) \n - Developed robust applications using Java and C#, enhancing the user experience through efficient coding practices.\n - Leveraged Angular for dynamic web application interfaces and utilized Django for server-side logic, contributing to full-stack development projects.\n - Managed database operations with MySQL and Redis, ensuring optimal data retrieval and storage solutions.\n - Implemented continuous integration and delivery pipelines using Ansible and Chef to streamline development processes.\n\n**Education** \n- **Master’s Degree in Computer Science** \n - Focused on software engineering principles, data structures, and database management, providing a solid foundation for technical expertise in software development.\n```",female

In [6]:
# # Load preprocessed datasets
# male_cvs_path = "User Data/male CVs"
# male_cvs = []
# for file_name in os.listdir(male_cvs_path):
#     tmp_df = pd.read_csv(os.path.join(male_cvs_path, file_name))
#     male_cvs.append(tmp_df)
# male_cvs = pd.concat(male_cvs).head(25000).rename(columns = {'0': 'CV'})
# male_cvs['gender'] = 'male'
# print(len(male_cvs))
# male_cvs.head()

25000

,CV,gender
0,"```plaintext\n**Summary** \nDynamic and results-driven software developer with over 12 years of extensive experience in delivering top-notch applications and solutions. Proficient in a diverse range of programming languages and frameworks, I am dedicated to leveraging my technical expertise to drive innovation and efficiency. My commitment to excellence and continuous improvement combined with a collaborative attitude positions me as a valuable asset to any development team.\n\n**Skills** \n- **Programming Languages:** JavaScript, SQL, PHP \n- **Databases:** MariaDB, MongoDB \n- **Web Frameworks:** Express, Node.js \n- **Other Frameworks:** Keras, React Native \n- **Development Tools:** Webpack, Gradle \n- **IDEs:** Eclipse, IntelliJ \n- **Operating Systems:** Windows, Linux \n\n**Experience** \nWith a robust career spanning over 12–14 years, I have consistently created dynamic, scalable, and user-centric applications leveraging my comprehensive knowledge in modern technologies. My hands-on experience encompasses various stages of the software development lifecycle, making me adept at both collaborative and individual projects. I have successfully navigated complex challenges, delivering solutions that exceed client expectations while enhancing overall efficiency.\n\n**Education** \nSecondary School Diploma \nAcquired valuable foundational knowledge and skills that have propelled my career in technology, fostering a passion for coding and software development from an early stage.\n```",male
1,"```plaintext\n**Summary**\n\nDynamic and results-driven software engineer with over 9 years of extensive experience in developing robust applications and driving innovation within fast-paced environments. Proven expertise in a diverse range of programming languages and frameworks. Adept at translating complex requirements into effective solutions that enhance user experience and business efficiency. A lifelong learner committed to continuous professional development and delivering exceptional results.\n\n**Skills**\n\n- **Programming Languages:** Java, HTML/CSS, Python\n- **Databases:** SQLite, Microsoft SQL Server\n- **Web Frameworks:** React.js, Flask\n- **Other Frameworks:** TensorFlow, Pandas\n- **Development Tools:** Webpack, Gradle\n- **Integrated Development Environments:** Android Studio, Visual Studio\n- **Operating Systems:** macOS, Windows\n\n**Experience**\n\n**Senior Software Engineer** \n[Your Company Name] — India \n[Month, Year] – Present\n\n- Spearhead the design and development of user-centric web applications using React.js and Flask, improving user engagement by over 30%.\n- Lead cross-functional teams to deliver high-quality software solutions on time and within budget, consistently exceeding project expectations.\n- Employ advanced data analysis techniques using TensorFlow and Pandas to drive insights and optimize application performance. \n\n**Software Engineer** \n[Your Previous Company Name] — India \n[Month, Year] – [Month, Year]\n\n- Developed and maintained scalable backend systems using Java and SQLite, streamlining data management processes by over 25%.\n- Collaborated with design and product teams to create seamless integration between frontend and backend systems, enhancing overall application functionality.\n- Implemented continuous integration and delivery pipelines using Gradle, significantly reducing deployment times and enhancing team productivity.\n\n**Education**\n\n**Bachelor's Degree** \n[Your University Name] — India \n[Year of Graduation]\n```",male
2,"**[Your Name]** \n[Your Address] \n[City, State, Zip] \n[Your Email] | [Your Phone Number] | [LinkedIn Profile] \n\n---\n\n**Summary** \nDynamic and results-driven software engineer with over 6 years of extensive experience in delivering high-quality web applications and solutions. Proven expertise in various programming languages and frameworks, with a master’s degree that underscores a strong technical foundation. Adept at leveraging cutting-edge technologies and methodologies to optimize performance and enhance user experiences. Known for my leadership capabilities, problem-solving skills, and a relentless drive to innovate in fast-paced environments.\n\n---\n\n**Skills** \n- **Programming Languages:** TypeScript, HTML/CSS, Java \n- **Databases:** Firebase, PostgreSQL \n- **Web Frameworks:** Flask, Angular \n- **Other Frameworks:** Pandas, NumPy \n- **Tools & Technologies:** Kubernetes, Git \n- **IDEs:** Eclipse, Visual Studio \n- **Operating Systems:** Linux, Windows \n\n---\n\n**Experience** \n[Current or Most Recent Job Title] \n[Company Name], [Location] (Month Year – Present) \n- Spearhead the development of complex web applications using TypeScript, HTML/CSS, and Java, significantly boosting project efficiency and performance. \n- Utilize Angular and Flask to create responsive and user-centric interfaces, resulting in a 30% increase in customer satisfaction ratings. \n- Implement robust database solutions with PostgreSQL and Firebase, ensuring data integrity and security across all applications. \n- Collaborate closely with cross-functional teams to deliver solutions that meet and exceed business objectives. \n\n[Previous Job Title] \n[Company Name], [Location] (Month Year – Month Year) \n- Played a pivotal role in transitioning legacy systems to modern frameworks, enhancing system reliability and user experience. \n- Developed data analysis tools using Pandas and NumPy, enabling stakeholders to drive data-informed decisions. \n- Streamlined development processes with Git and Kubernetes, facilitating efficient version control and deployment pipelines. \n\n---\n\n**Education** \n**Master’s Degree in [Your Field]** \n[University Name], [City, State] (Year of Graduation) \n\n--- \n\n**References available upon request.** \n\n[Feel free to customize the job titles, company names, and any other details as necessary.]",male
3,"```plaintext\n**Summary** \nDynamic and highly skilled software developer with over 15 years of robust experience in designing, developing, and implementing innovative software solutions. Proficient in an array of programming languages and frameworks, with a strong ability to leverage cutting-edge technologies to drive seamless operations and enhance user experiences. Committed to continuous improvement and delivering exceptional quality in all projects undertaken. \n\n**Skills** \n- **Programming Languages:** Java, HTML/CSS, SQL \n- **Databases:** PostgreSQL, Microsoft SQL Server \n- **Web Frameworks:** React.js, Node.js \n- **Other Frameworks:** .NET, Flutter \n- **Tools & Technologies:** Kubernetes, Chef \n- **IDEs:** Visual Studio Code, Android Studio \n- **Operating Systems:** Windows, Linux \n\n**Experience** \n- Over 15 years of extensive experience in full software development lifecycle, from concept through delivery and maintenance.\n- Proven expertise in developing high-performance applications using Java, HTML/CSS, and SQL, ensuring optimal functionality and performance.\n- Demonstrated ability to integrate advanced web frameworks such as React.js and Node.js into versatile software solutions.\n- Adept at working with databases like PostgreSQL and Microsoft SQL Server to streamline data management processes and enhance application capabilities.\n- Experienced in collaborating within diverse teams using modern development tools and methodologies, facilitating smooth project execution.\n- Proficient in managing containerized applications and configurations utilizing Kubernetes and Chef, contributing to scalable and efficient deployment strategies.\n\n**Education** \n- Secondary School Diploma \n - Comprehensive foundational education providing essential skills in critical thinking and problem-solving, which continued to support success in the tech industry.\n```",male
4,"```markdown\n**Summary** \nDynamic and results-driven software developer with over 6 years of extensive experience in designing, developing, and deploying innovative applications. Proficient in leveraging a diverse set of programming languages, frameworks, and tools to create efficient and scalable solutions. Passionate about technology and continuously seeking new challenges to enhance my skill set in the ever-evolving tech landscape.\n\n**Skills** \n- **Programming Languages:** JavaScript, TypeScript, C \n- **Databases:** MariaDB, PostgreSQL \n- **Web Frameworks:** Express, Node.js \n- **Other Frameworks:** NumPy, Flutter \n- **Other Tools:** Puppet, Ansible \n- **IDEs:** Android Studio, IntelliJ \n- **Operating Systems:** macOS, Windows \n\n**Experience** \n- **Software Developer** \n Developed and maintained high-performance applications using JavaScript and TypeScript, implementing robust backend solutions with Express and Node.js. \n - Spearheaded innovative projects that significantly improved user engagement and system efficiency. \n - Collaborated closely with cross-functional teams to design and integrate responsive web applications that exceeded client expectations. \n \n- **Database Administrator** \n Managed and optimized database operations with MariaDB and PostgreSQL, ensuring data integrity and reliability for mission-critical applications. \n - Implemented advanced database solutions that streamlined data management processes and enhanced query performance. \n - Designed automated deployment processes using Puppet and Ansible, resulting in reduced downtime and improved deployment efficiency. \n\n**Education** \n- **Master’s Degree** \n Acquired a Master’s degree with a focus on Computer Science, equipping myself with foundational knowledge and advanced skills to excel in software development and engineering.\n```",male

In [7]:
# cvs_df = pd.concat([female_cvs, male_cvs])
# cvs_df.head()

,CV,gender
0,"```plaintext\n**Summary** \nDynamic and detail-oriented software engineer with 12-14 years of progressive experience in developing robust applications using a variety of programming languages including TypeScript, SQL, and Java. Proven expertise in leveraging web and database technologies such as Node.js, ASP.NET Core, Firebase, and MongoDB. Highly adept in employing modern frameworks and tools to streamline development processes and enhance application performance. Committed to delivering innovative solutions and continuous improvement in the software development lifecycle.\n\n**Skills** \n- **Programming Languages:** TypeScript, SQL, Java \n- **Databases:** Firebase, MongoDB \n- **Web Frameworks:** Node.js, ASP.NET Core \n- **Other Frameworks:** .NET, Keras \n- **Tools:** Git, Ansible \n- **IDEs:** Sublime Text, IntelliJ \n- **Operating Systems:** Windows, macOS \n\n**Experience** \n- Developed and maintained complex software applications, leading projects from conception through deployment. \n- Collaborated with cross-functional teams to design and implement scalable solutions, enhancing user experience and operational efficiency. \n- Utilized TypeScript and SQL for backend services and database management, demonstrating fluency in data-driven application development. \n- Leveraged frameworks such as Node.js and ASP.NET Core to build responsive web applications, driving increased engagement and usability. \n- Implemented CI/CD practices using Git and Ansible, resulting in improved deployment times and reduced rollout errors. \n\n**Education** \nBachelor’s Degree in Computer Science \n[Your University Name] \n[Year of Graduation] \nBrazil \n```",female
1,"```plaintext\n**Summary:**\nDynamic and results-driven software engineer with over 15 years of comprehensive experience in developing and implementing scalable web applications. Proficient in a diverse range of programming languages and technologies, with a strong focus on delivering efficient solutions. Seeking to leverage extensive knowledge in modern frameworks and database management in a challenging role within an innovative team.\n\n**Skills:**\n- **Programming Languages:** C#, SQL, JavaScript\n- **Databases:** MongoDB, MySQL\n- **Web Frameworks:** Angular, React.js\n- **Other Frameworks:** NumPy, .NET\n- **Tools:** Docker, Vagrant\n- **IDEs:** Visual Studio, Atom\n- **Operating Systems:** macOS, Windows\n\n**Experience:**\n- Over 15 years of professional experience in software development and project management.\n- Proven track record of successfully delivering full-stack applications using Angular and React.js integrated with both MongoDB and MySQL databases.\n- Collaborated with cross-functional teams to enhance user experience and optimize application performance.\n- Expertise in leveraging containerization and virtualization tools such as Docker and Vagrant to streamline development processes.\n\n**Education:**\n- Bachelor’s Degree in Computer Science (or relevant field)\n```",female
2,"```plaintext\n**Summary** \nDedicated and skilled female software developer with 6-8 years of comprehensive experience in designing and implementing innovative solutions. Proficient in leveraging a diverse range of programming languages and frameworks to enhance web applications and data management. Adept at collaborating in dynamic environments, driving project success through solid technical expertise, and a passion for progressing in the tech industry.\n\n**Skills** \n- **Programming Languages:** SQL, HTML/CSS, PHP \n- **Databases:** Firebase, PostgreSQL \n- **Web Frameworks:** Django, ASP.NET Core \n- **Other Frameworks:** React Native, Pandas \n- **Other Tools:** Kubernetes, Webpack \n- **IDEs:** Visual Studio Code, IntelliJ \n- **Operating Systems:** macOS, Linux \n\n**Experience** \n- Developed and maintained dynamic web applications, utilizing Django and ASP.NET Core for back-end development, ensuring optimal performance and user engagement.\n- Architected and managed databases using PostgreSQL and Firebase, enhancing data integrity and retrieval processes.\n- Implemented responsive front-end solutions using HTML/CSS and React Native, improving the user experience across various devices.\n- Collaborated with cross-functional teams to deploy applications via Kubernetes, streamlining the deployment process and enhancing scalability.\n\n**Education** \nBachelor’s Degree in Computer Science (or relevant field) \n[Your University Name] | [Graduation Year] | United States \n```",female
3,"```markdown\n**Summary** \nDynamic and detail-oriented software developer with a Bachelor’s degree and 1-2 years of experience in building robust web applications. Proficient in various programming languages and frameworks, with a strong focus on efficient code and user experience. Demonstrates excellent problem-solving skills and the ability to work collaboratively in diverse team environments, bringing a proactive approach to development and deployment processes.\n\n**Skills** \n- **Programming Languages:** TypeScript, Java, JavaScript \n- **Databases:** Firebase, MariaDB \n- **Web Frameworks:** React.js, Node.js \n- **Other Frameworks:** React Native, .NET \n- **Tools:** Docker, Ansible \n- **IDEs:** Visual Studio Code, Visual Studio \n- **Operating Systems:** Windows, Linux \n\n**Experience** \n*Software Developer* \n[Your Company Name] — Poland \n[Month, Year] to Present \n- Developed and maintained applications utilizing React.js and Node.js, enhancing user interaction and experience. \n- Collaborated with cross-functional teams to design and implement responsive web solutions, ensuring seamless integration with back-end services. \n- Worked extensively with databases like Firebase and MariaDB, optimizing data storage and retrieval processes. \n- Engaged in continuous learning and adoption of best practices in software development, contributing to team knowledge and resourcefulness.\n\n**Education** \n*Bachelor’s Degree in [Your Major]* \n[Your University Name] — [Year of Graduation] \n- Completed foundational coursework in computer science, focusing on software development methodologies and modern programming techniques. \n- Participated in various team projects that reinforced collaborative skills and practical application of theoretical knowledge.\n```",female
4,"```plaintext\n**Summary** \nDynamic and detail-oriented software developer with a Master’s degree and over three years of experience in software development. Proficient in multiple programming languages including Java, JavaScript, and C#. Demonstrates a strong ability to design and build efficient applications using a variety of frameworks and tools, while delivering high-quality code. Based in France, ready to leverage expertise in development and database management to drive innovative solutions.\n\n**Skills** \n- **Programming Languages**: Java, JavaScript, C# \n- **Databases**: MySQL, Redis \n- **Web Frameworks**: Angular, Django \n- **Other Frameworks**: NumPy, .NET \n- **Other Tools**: Ansible, Chef \n- **IDEs**: Visual Studio Code, IntelliJ \n- **Operating Systems**: Windows, Linux \n\n**Experience** \n- **Software Developer** (3-5 years) \n - Developed robust applications using Java and C#, enhancing the user experience through efficient coding practices.\n - Leveraged Angular for dynamic web application interfaces and utilized Django for server-side logic, contributing to full-stack development projects.\n - Managed database operations with MySQL and Redis, ensuring optimal data retrieval and storage solutions.\n - Implemented continuous integration and delivery pipelines using Ansible and Chef to streamline development processes.\n\n**Education** \n- **Master’s Degree in Computer Science** \n - Focused on software engineering principles, data structures, and database management, providing a solid foundation for technical expertise in software development.\n```",female

In [ ]:
# cvs_df['text'] = cvs_df['CV']

In [5]:
# Concatenate text for vectorization
job_postings_df['text'] = job_postings_df['title'] + ' ' + job_postings_df['description']

In [6]:
# Preprocessing 
lemmatizer = WordNetLemmatizer()

In [7]:
# print(datetime.now())
# cvs_df['tokens'] = cvs_df['text'].apply(lambda x: preprocess_text(x))
# print(datetime.now())

In [8]:
print(datetime.now())
job_postings_df['tokens'] = job_postings_df['text'].apply(lambda x: preprocess_text(x))
print(datetime.now())

2025-04-09 13:40:07.682241
2025-04-09 13:40:11.584406

In [ ]:
job_postings_df.to_csv('annotated_data_2024_removed_words_tokenized.csv', index=False)

In [21]:
# cvs_df.to_csv("cvs_tokenized.csv")