In [1]:
import pandas as pd
import numpy as np
import gensim
import re
import os
import nltk
from tqdm import tqdm 
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from gensim.models import Word2Vec
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from gensim.similarities import WmdSimilarity
from gensim.models import Phrases

pd.set_option('display.max_colwidth', None)

In [2]:
jobs_data_dir = "Job Data\\"
dataframes = []
# Read all files in the directory
for file_name in os.listdir(jobs_data_dir):
    if '2024' in file_name: 
        print(file_name)
        file_path = os.path.join(jobs_data_dir, file_name)
        tmp_df = pd.read_csv(file_path, usecols = ['jobPostingId', 'title', 'description', 'tokens', 'gender_category'])
        tmp_df = tmp_df.dropna(how='any')
        dataframes.append(tmp_df)
job_postings_df = pd.concat(dataframes)
print(len(job_postings_df))
job_postings_df.head()

annotated_data_2024_batch_2_removed_words_tokenized.csv
annotated_data_2024_removed_words_tokenized.csv
77975

,jobPostingId,title,description,gender_category,tokens
0,3823301365,Python Full Stack Developer/Lead/Architect,"Skills- Python, Django, React/AngularExperience- 4+ yrsLocation- Hyderabad\nJob Description-\nâ¢ Python + Django, Angular/React Develop, and maintain robust, scalable backend systems using Python.â¢ Ensure technology solutions align with company architectural standards.â¢ Collaborate seamlessly with cross-functional teams for the integration of platform services.â¢ Foster close collaboration with frontend developers, ensuring a harmonious backend-frontend integration.â¢ Proactively identify and resolve issues promptly.â¢ Strong full-stack development skills in Python, including expertise in frameworks like Django (Expert).â¢ Experience with microservice architecture, end-to-end UI/API integration, and knowledge of API protocols like REST, gRPC, and GraphQL (Advanced).â¢ Knowledge of Caching technologies and DBMS technologies like MySQL, PostGres, MongoDB, and database schema design (Advanced).â¢ Strong problem-solving, communication, and organizational skills (Advanced).â¢ Proficiency in UI modern x like AngularJS or ReactJS (Intermediate).â¢ Proficient in drafting coding practices and designing highly scalable, secure, and maintainable software solutions (Intermediate).â¢ Experience in building large-scale platforms handling real-time complex transactions and troubleshooting distributed systems (Intermediate).",fem,"['python', 'full', 'stack', 'python', 'django', 'hyderabad', 'job', 'python', 'django', 'develop', 'maintain', 'robust', 'scalable', 'backend', 'system', 'using', 'ensure', 'technology', 'solution', 'align', 'company', 'architectural', 'collaborate', 'seamlessly', 'team', 'integration', 'platform', 'foster', 'close', 'collaboration', 'frontend', 'developer', 'ensuring', 'harmonious', 'proactively', 'identify', 'resolve', 'issue', 'strong', 'development', 'skill', 'python', 'including', 'expertise', 'framework', 'like', 'django', 'expert', 'experience', 'microservice', 'architecture', 'integration', 'knowledge', 'api', 'protocol', 'like', 'rest', 'grpc', 'graphql', 'advanced', 'knowledge', 'caching', 'technology', 'dbms', 'technology', 'like', 'mysql', 'postgres', 'mongodb', 'database', 'schema', 'design', 'advanced', 'strong', 'communication', 'organizational', 'skill', 'advanced', 'proficiency', 'ui', 'modern', 'x', 'like', 'angularjs', 'reactjs', 'intermediate', 'proficient', 'drafting', 'coding', 'practice', 'designing', 'highly', 'scalable', 'secure', 'maintainable', 'software', 'solution', 'intermediate', 'experience', 'building', 'platform', 'handling', 'complex', 'transaction', 'troubleshooting', 'distributed', 'system', 'intermediate']"
1,3823301077,Senior Data Engineer - w2 only,"Expertise:8+ years of relevant industry experience with a BS/MastersExperience with distributed processing technologies and frameworks, such as Hadoop, Spark, Kafka, and distributed storage systems (e.g., HDFS, S3)Demonstrated ability to analyze large data sets to identify gaps and inconsistencies, provide data insights, and advance effective product solutionsExpertise with ETL schedulers such as Apache Airflow, Luigi, Oozie, AWS Glue or similar frameworksSolid understanding of data warehousing concepts and hands-on experience with relational databases (e.g., PostgreSQL, MySQL) and columnar databases (e.g., Redshift, BigQuery, HBase, ClickHouse)Excellent written and verbal communication skillsA Typical Day:Design, build, and maintain robust and efficient data pipelines that collect, process, and store data from various sources, including user interactions, financial details, and external data feeds.Develop data models that enable the efficient analysis and manipulation of data for merchandising optimization. Ensure data quality, consistency, and accuracy.Build scalable data pipelines (SparkSQL & Scala) leveraging Airflow scheduler/executor frameworkCollaborate with cross-functional teams, including Data Scientists, Product Managers, and Software Engineers, to define data requirements, and deliver data solutions that drive merchandising and sales improvements.Contribute to the broader Data Engineering community at Airbnb to influence tooling and standards to improve culture and productivityImprove code and data quality by leveraging and contributing to internal tools to automatically detect and mitigate issues.\n",neutral,"['senior', 'data', 'engineer', 'year', 'relevant', 'industry', 'experience', 'distributed', 'processing', 'technology', 'framework', 'hadoop', 'spark', 'kafka', 'distributed', 'storage', 'system', 'hdfs', 'demonstrated', 'ability', 'analyze', 'large', 'data', 'set', 'identify', 'gap', 'inconsistency', 'provide', 'data', 'insight', 'advance', 'effective', 'product', 'solutionsexpertise', 'etl', 'scheduler', 'apache', 'airflow', 'luigi', 'oozie', 'aws', 'glue', 'similar', 'frameworkssolid', 'understanding', 'data', 'warehousing', 'concept', 'experience', 'relational', 'database', 'postgresql', 'mysql', 'columnar', 'database', 'redshift', 'bigquery', 'hbase', 'clickhouse', 'excellent', 'written', 'verbal', 'communication', 'skillsa', 'typical', 'day', 'design', 'build', 'maintain', 'robust', 'efficient', 'data', 'pipeline', 'collect', 'process', 'store', 'data', 'various', 'source', 'including', 'user', 'interaction', 'financial', 'detail', 'external', 'data', 'data', 'model', 'enable', 'efficient', 'analysis', 'manipulation', 'data', 'merchandising', 'optimization', 'ensure', 'data', 'quality', 'consistency', 'scalable', 'data', 'pipeline', 'sparksql', 'scala', 'leveraging', 'airflow', 'frameworkcollaborate', 'team', 'including', 'data', 'scientist', 'product', 'manager', 'software', 'engineer', 'define', 'data', 'requirement', 'deliver', 'data', 'solution', 'drive', 'merchandising', 'sale', 'broader', 'data', 'engineering', 'community', 'airbnb', 'influence', 'tooling', 'standard', 'improve', 'culture', 'productivityimprove', 'code', 'data', 'quality', 'leveraging', 'contributing', 'internal', 'tool', 'automatically', 'detect', 'mitigate', 'issue']"
2,3823301053,Retail Front End Supervisor,"LOCATION 1130 Newport Avenue Attleboro MA US 02703\n\nOverview\n\nAt Burlington, we embrace the many facets of diversity that strengthen our communities where we live and work every day. If you want to grow your retail career with a caring and inclusive organization, come join us as a Burlington Stores Full-Time Customer Service Supervisor or Full-Time Selling Floor Supervisor!\n\nAs a Retail Front End Supervisor, youâll be an integral part of the store leadership team, working closely with Store Management in the areas of Merchandising, Customer Service, Operations, and Human Resources. This leadership position is the stepping-stone to a management role within our expanding organization. Are you a self-starter with the ability to supervise store operations efficiently and effectively? If you are a proven leader who understands the value of building strong teams and partnerships to drive results, this is the right opportunity for you!\n\nAt Burlington, we live by our Core Values:\n\nDrive ResultsTrust & Respect Each OtherBuild Teams & Partnerships\n\nBurlington Benefits:\n\nGrowth OpportunitiesCompetitive PayFlexible Hours15-30% Associate DiscountMedical, Dental, and Vision CoverageEmployee Assistance ProgramLife and Disability InsurancePaid Time OffPaid Holidays401 (k)\n\nKey Responsibilities:\n\nSupervise all store functions and associates while in the role of Manager on DutyMaximize sales results through training, developing, and coaching of direct reportsPromote safety for both our customers and associates by adhering to company guidelinesCultivate a diverse culture based on teamwork and collaborationSolve issues/concerns, making informed decisions and supervising the front-end operations to ensure all Burlington customers are provided with exceptional, friendly, and professional customer service at all timesReinforce our company Asset Protection strategies to eliminate shortageAssist in recruiting, interviewing, and onboarding new associatesParticipate in weekly workload planning meetingsDrives Community Relations participation through company programs and partnershipsCoordinate meal and break periods and monitors schedule adherence\n\nRequirements:\n\nAt least 1 year of supervisory experience within an off-price, big box or a specialty environmentStrong interpersonal skills with a positive and engaging attitudeAbility to work a full-time schedule including nights, weekends and holidays as requiredAbility to move/handle/lift store merchandise weighing 40 lbs. or more, as well as the ability to stand and walk for extended periods of time\n\nAt Burlington weâre opening more stores nationwide to provide you with even more locations to enjoy our amazing prices on the brands and styles you love. As we grow, you can too through a variety of training and development opportunities!\n\nCome join our team. Youâre going to like it here!\n\nYou will enjoy a competitive wage, flexible hours, and an associate discount. Burlington's benefits package includes medical, dental, and vision coverage including life and disability insurance. Full time associates may also be eligible for up to 12 days of paid time off annually, up to 8 paid holidays, paid sick time in accordance with applicable law, and a 401(k) plan. We are a rapidly growing brand and provide a variety of training and development opportunities so our associates can grow with us.\n\nOur store teams work hard and have fun together! Burlington associates make a difference in the lives of customers, colleagues, and the communities where we live and work every day. Burlington Stores, Inc. is an equal opportunity employer committed to workplace diversity.\n\nLocation US-MA-Attleboro\n\nPosting Number 2024-214348\n\nAddress 1130 Newport Avenue\n\nZip Code 02703\n\nWorkplace Type On-Site\n\nPosition Type Regular Full-Time\n\nCareer Site Category Store Associate\n\nPosition Category Store Supervisor\n\nEvergreen Yes\n\nMin USD $17.50/Hour\n\nMid USD $19.50/Hour",masc,"['retail', 'front', 'end', 'supervisor', 'location', 'newport', 'avenue', 'attleboro', 'u', 'overview', 'burlington', 'embrace', 'many', 'facet', 'diversity', 'strengthen', 'community', 'live', 'work', 'every', 'day', 'want', 'grow', 'retail', 'career', 'caring', 'inclusive', 'organization', 'come', 'join', 'u', 'burlington', 'store', 'customer', 'service', 'supervisor', 'selling', 'floor', 'supervisor', 'retail', 'front', 'end', 'supervisor', 'integral', 'part', 'store', 'leadership', 'team', 'working', 'closely', 'store', 'management', 'area', 'merchandising', 'customer', 'service', 'operation', 'human', 'resource', 'leadership', 'position', 'management', 'role', 'within', 'expanding', 'organization', 'ability', 'supervise', 'store', 'operation', 'efficiently', 'effectively', 'proven', 'leader', 'understands', 'value', 'building', 'strong', 'team', 'partnership', 'drive', 'result', 'right', 'opportunity', 'burlington', 'live', 'core', 'value', 'drive', 'resultstrust', 'respect', 'otherbuild', 'team', 'partnership', 'burlington', 'benefit', 'growth', 'opportunitiescompetitive', 'payflexible', 'associate', 'discountmedical', 'dental', 'vision', 'coverageemployee', 'assistance', 'programlife', 'disability', 'insurancepaid', 'time', 'offpaid', 'k', 'key', 'responsibility', 'supervise', 'store', 'function', 'associate', 'role', 'manager', 'dutymaximize', 'sale', 'result', 'training', 'developing', 'coaching', 'direct', 'reportspromote', 'safety', 'customer', 'associate', 'adhering', 'company', 'guidelinescultivate', 'diverse', 'culture', 'based', 'teamwork', 'collaborationsolve', 'making', 'informed', 'decision', 'supervising', 'operation', 'ensure', 'burlington', 'customer', 'provided', 'exceptional', 'friendly', 'professional', 'customer', 'service', 'timesreinforce', 'company', 'asset', 'protection', 'strategy', 'eliminate', 'shortageassist', 'recruiting', 'interviewing', 'onboarding', 'new', 'associatesparticipate', 'weekly', 'workload', 'planning', 'meetingsdrives', 'community', 'relation', 'participation', 'company', 'program', 'partnershipscoordinate', 'meal', 'break', 'period', 'monitor', 'schedule', 'adherence', 'requirement', 'least', 'year', 'supervisory', 'experience', 'within', 'big', 'box', 'specialty', 'environmentstrong', 'interpersonal', 'skill', 'positive', 'engaging', 'attitudeability', 'work', 'schedule', 'including', 'night', 'weekend', 'holiday', 'requiredability', 'store', 'merchandise', 'weighing', 'lb', 'well', 'ability', 'stand', 'walk', 'extended', 'period', 'time', 'burlington', 'opening', 'store', 'nationwide', 'provide', 'even', 'location', 'enjoy', 'amazing', 'price', 'brand', 'style', 'love', 'grow', 'variety', 'training', 'development', 'opportunity', 'come', 'join', 'team', 'going', 'like', 'enjoy', 'competitive', 'wage', 'flexible', 'hour', 'associate', 'discount', 'burlington', 'benefit', 'package', 'includes', 'medical', 'dental', 'vision', 'coverage', 'including', 'life', 'disability', 'insurance', 'full', 'time', 'associate', 'may', 'also', 'eligible', 'day', 'paid', 'time', 'annually', 'paid', 'holiday', 'paid', 'sick', 'time', 'accordance', 'applicable', 'law', 'k', 'plan', 'rapidly', 'growing', 'brand', 'provide', 'variety', 'training', 'development', 'opportunity', 'associate', 'grow', 'u', 'store', 'team', 'work', 'hard', 'fun', 'together', 'burlington', 'associate', 'make', 'difference', 'life', 'customer', 'colleague', 'community', 'live', 'work', 'every', 'day', 'burlington', 'store', 'equal', 'opportunity', 'employer', 'committed', 'workplace', 'diversity', 'location', 'posting', 'number', 'address', 'newport', 'avenue', 'zip', 'code', 'workplace', 'type', 'position', 'type', 'regular', 'career', 'site', 'category', 'store', 'associate', 'position', 'category', 'store', 'supervisor', 'evergreen', 'yes', 'min', 'usd', 'mid', 'usd']"

In [3]:
cvs_df = pd.read_csv("User Data/cvs_tokenized_final.csv")
cvs_df.head()

,CV,gender,text,tokens
0,"```plaintext\n**Summary** \nDynamic and detail-oriented software engineer with 12-14 years of progressive experience in developing robust applications using a variety of programming languages including TypeScript, SQL, and Java. Proven expertise in leveraging web and database technologies such as Node.js, ASP.NET Core, Firebase, and MongoDB. Highly adept in employing modern frameworks and tools to streamline development processes and enhance application performance. Committed to delivering innovative solutions and continuous improvement in the software development lifecycle.\n\n**Skills** \n- **Programming Languages:** TypeScript, SQL, Java \n- **Databases:** Firebase, MongoDB \n- **Web Frameworks:** Node.js, ASP.NET Core \n- **Other Frameworks:** .NET, Keras \n- **Tools:** Git, Ansible \n- **IDEs:** Sublime Text, IntelliJ \n- **Operating Systems:** Windows, macOS \n\n**Experience** \n- Developed and maintained complex software applications, leading projects from conception through deployment. \n- Collaborated with cross-functional teams to design and implement scalable solutions, enhancing user experience and operational efficiency. \n- Utilized TypeScript and SQL for backend services and database management, demonstrating fluency in data-driven application development. \n- Leveraged frameworks such as Node.js and ASP.NET Core to build responsive web applications, driving increased engagement and usability. \n- Implemented CI/CD practices using Git and Ansible, resulting in improved deployment times and reduced rollout errors. \n\n**Education** \nBachelorâ€™s Degree in Computer Science \n[Your University Name] \n[Year of Graduation] \nBrazil \n```",female,"```plaintext\n**Summary** \nDynamic and detail-oriented software engineer with 12-14 years of progressive experience in developing robust applications using a variety of programming languages including TypeScript, SQL, and Java. Proven expertise in leveraging web and database technologies such as Node.js, ASP.NET Core, Firebase, and MongoDB. Highly adept in employing modern frameworks and tools to streamline development processes and enhance application performance. Committed to delivering innovative solutions and continuous improvement in the software development lifecycle.\n\n**Skills** \n- **Programming Languages:** TypeScript, SQL, Java \n- **Databases:** Firebase, MongoDB \n- **Web Frameworks:** Node.js, ASP.NET Core \n- **Other Frameworks:** .NET, Keras \n- **Tools:** Git, Ansible \n- **IDEs:** Sublime Text, IntelliJ \n- **Operating Systems:** Windows, macOS \n\n**Experience** \n- Developed and maintained complex software applications, leading projects from conception through deployment. \n- Collaborated with cross-functional teams to design and implement scalable solutions, enhancing user experience and operational efficiency. \n- Utilized TypeScript and SQL for backend services and database management, demonstrating fluency in data-driven application development. \n- Leveraged frameworks such as Node.js and ASP.NET Core to build responsive web applications, driving increased engagement and usability. \n- Implemented CI/CD practices using Git and Ansible, resulting in improved deployment times and reduced rollout errors. \n\n**Education** \nBachelorâ€™s Degree in Computer Science \n[Your University Name] \n[Year of Graduation] \nBrazil \n```","['plaintext', 'summary', 'dynamic', 'software', 'engineer', 'year', 'progressive', 'experience', 'developing', 'robust', 'application', 'using', 'variety', 'programming', 'language', 'including', 'typescript', 'sql', 'java', 'proven', 'expertise', 'leveraging', 'web', 'database', 'technology', 'core', 'firebase', 'mongodb', 'highly', 'adept', 'employing', 'modern', 'framework', 'tool', 'streamline', 'development', 'process', 'enhance', 'application', 'performance', 'committed', 'delivering', 'innovative', 'solution', 'continuous', 'improvement', 'software', 'development', 'lifecycle', 'skill', 'programming', 'language', 'typescript', 'sql', 'java', 'database', 'firebase', 'mongodb', 'web', 'framework', 'core', 'framework', 'kera', 'tool', 'git', 'ansible', 'ides', 'sublime', 'text', 'intellij', 'operating', 'system', 'window', 'macos', 'experience', 'developed', 'maintained', 'complex', 'software', 'application', 'leading', 'project', 'conception', 'deployment', 'collaborated', 'team', 'design', 'implement', 'scalable', 'solution', 'enhancing', 'user', 'experience', 'operational', 'efficiency', 'utilized', 'typescript', 'sql', 'backend', 'service', 'database', 'management', 'demonstrating', 'fluency', 'application', 'development', 'leveraged', 'framework', 'core', 'build', 'responsive', 'web', 'application', 'driving', 'increased', 'engagement', 'usability', 'implemented', 'practice', 'using', 'git', 'ansible', 'resulting', 'improved', 'deployment', 'time', 'reduced', 'rollout', 'error', 'education', 'bachelor', 'degree', 'computer', 'science', 'university', 'name', 'year', 'graduation', 'brazil']"
1,"```plaintext\n**Summary:**\nDynamic and results-driven software engineer with over 15 years of comprehensive experience in developing and implementing scalable web applications. Proficient in a diverse range of programming languages and technologies, with a strong focus on delivering efficient solutions. Seeking to leverage extensive knowledge in modern frameworks and database management in a challenging role within an innovative team.\n\n**Skills:**\n- **Programming Languages:** C#, SQL, JavaScript\n- **Databases:** MongoDB, MySQL\n- **Web Frameworks:** Angular, React.js\n- **Other Frameworks:** NumPy, .NET\n- **Tools:** Docker, Vagrant\n- **IDEs:** Visual Studio, Atom\n- **Operating Systems:** macOS, Windows\n\n**Experience:**\n- Over 15 years of professional experience in software development and project management.\n- Proven track record of successfully delivering full-stack applications using Angular and React.js integrated with both MongoDB and MySQL databases.\n- Collaborated with cross-functional teams to enhance user experience and optimize application performance.\n- Expertise in leveraging containerization and virtualization tools such as Docker and Vagrant to streamline development processes.\n\n**Education:**\n- Bachelorâ€™s Degree in Computer Science (or relevant field)\n```",female,"```plaintext\n**Summary:**\nDynamic and results-driven software engineer with over 15 years of comprehensive experience in developing and implementing scalable web applications. Proficient in a diverse range of programming languages and technologies, with a strong focus on delivering efficient solutions. Seeking to leverage extensive knowledge in modern frameworks and database management in a challenging role within an innovative team.\n\n**Skills:**\n- **Programming Languages:** C#, SQL, JavaScript\n- **Databases:** MongoDB, MySQL\n- **Web Frameworks:** Angular, React.js\n- **Other Frameworks:** NumPy, .NET\n- **Tools:** Docker, Vagrant\n- **IDEs:** Visual Studio, Atom\n- **Operating Systems:** macOS, Windows\n\n**Experience:**\n- Over 15 years of professional experience in software development and project management.\n- Proven track record of successfully delivering full-stack applications using Angular and React.js integrated with both MongoDB and MySQL databases.\n- Collaborated with cross-functional teams to enhance user experience and optimize application performance.\n- Expertise in leveraging containerization and virtualization tools such as Docker and Vagrant to streamline development processes.\n\n**Education:**\n- Bachelorâ€™s Degree in Computer Science (or relevant field)\n```","['plaintext', 'summary', 'dynamic', 'software', 'engineer', 'year', 'comprehensive', 'experience', 'developing', 'implementing', 'scalable', 'web', 'application', 'proficient', 'diverse', 'range', 'programming', 'language', 'technology', 'strong', 'focus', 'delivering', 'efficient', 'solution', 'seeking', 'leverage', 'extensive', 'knowledge', 'modern', 'framework', 'database', 'management', 'challenging', 'role', 'within', 'innovative', 'team', 'skill', 'programming', 'language', 'c', 'sql', 'javascript', 'database', 'mongodb', 'mysql', 'web', 'framework', 'angular', 'framework', 'numpy', 'tool', 'docker', 'vagrant', 'ides', 'visual', 'studio', 'atom', 'operating', 'system', 'macos', 'window', 'experience', 'year', 'professional', 'experience', 'software', 'development', 'project', 'management', 'proven', 'track', 'record', 'successfully', 'delivering', 'application', 'using', 'angular', 'integrated', 'mongodb', 'mysql', 'database', 'collaborated', 'team', 'enhance', 'user', 'experience', 'optimize', 'application', 'performance', 'expertise', 'leveraging', 'containerization', 'virtualization', 'tool', 'docker', 'vagrant', 'streamline', 'development', 'process', 'education', 'bachelor', 'degree', 'computer', 'science', 'relevant', 'field']"
2,"```plaintext\n**Summary** \nDedicated and skilled female software developer with 6-8 years of comprehensive experience in designing and implementing innovative solutions. Proficient in leveraging a diverse range of programming languages and frameworks to enhance web applications and data management. Adept at collaborating in dynamic environments, driving project success through solid technical expertise, and a passion for progressing in the tech industry.\n\n**Skills** \n- **Programming Languages:** SQL, HTML/CSS, PHP \n- **Databases:** Firebase, PostgreSQL \n- **Web Frameworks:** Django, ASP.NET Core \n- **Other Frameworks:** React Native, Pandas \n- **Other Tools:** Kubernetes, Webpack \n- **IDEs:** Visual Studio Code, IntelliJ \n- **Operating Systems:** macOS, Linux \n\n**Experience** \n- Developed and maintained dynamic web applications, utilizing Django and ASP.NET Core for back-end development, ensuring optimal performance and user engagement.\n- Architected and managed databases using PostgreSQL and Firebase, enhancing data integrity and retrieval processes.\n- Implemented responsive front-end solutions using HTML/CSS and React Native, improving the user experience across various devices.\n- Collaborated with cross-functional teams to deploy applications via Kubernetes, streamlining the deployment process and enhancing scalability.\n\n**Education** \nBachelorâ€™s Degree in Computer Science (or relevant field) \n[Your University Name] | [Graduation Year] | United States \n```",female,"```plaintext\n**Summary** \nDedicated and skilled female software developer with 6-8 years of comprehensive experience in designing and implementing innovative solutions. Proficient in leveraging a diverse range of programming languages and frameworks to enhance web applications and data management. Adept at collaborating in dynamic environments, driving project success through solid technical expertise, and a passion for progressing in the tech industry.\n\n**Skills** \n- **Programming Languages:** SQL, HTML/CSS, PHP \n- **Databases:** Firebase, PostgreSQL \n- **Web Frameworks:** Django, ASP.NET Core \n- **Other Frameworks:** React Native, Pandas \n- **Other Tools:** Kubernetes, Webpack \n- **IDEs:** Visual Studio Code, IntelliJ \n- **Operating Systems:** macOS, Linux \n\n**Experience** \n- Developed and maintained dynamic web applications, utilizing Django and ASP.NET Core for back-end development, ensuring optimal performance and user engagement.\n- Architected and managed databases using PostgreSQL and Firebase, enhancing data integrity and retrieval processes.\n- Implemented responsive front-end solutions using HTML/CSS and React Native, improving the user experience across various devices.\n- Collaborated with cross-functional teams to deploy applications via Kubernetes, streamlining the deployment process and enhancing scalability.\n\n**Education** \nBachelorâ€™s Degree in Computer Science (or relevant field) \n[Your University Name] | [Graduation Year] | United States \n```","['plaintext', 'summary', 'dedicated', 'skilled', 'female', 'software', 'developer', 'year', 'comprehensive', 'experience', 'designing', 'implementing', 'innovative', 'solution', 'proficient', 'leveraging', 'diverse', 'range', 'programming', 'language', 'framework', 'enhance', 'web', 'application', 'data', 'management', 'adept', 'collaborating', 'dynamic', 'environment', 'driving', 'project', 'success', 'solid', 'technical', 'expertise', 'passion', 'progressing', 'tech', 'industry', 'skill', 'programming', 'language', 'sql', 'php', 'database', 'firebase', 'postgresql', 'web', 'framework', 'django', 'core', 'framework', 'react', 'native', 'panda', 'tool', 'kubernetes', 'webpack', 'ides', 'visual', 'studio', 'code', 'intellij', 'operating', 'system', 'macos', 'linux', 'experience', 'developed', 'maintained', 'dynamic', 'web', 'application', 'utilizing', 'django', 'core', 'development', 'ensuring', 'optimal', 'performance', 'user', 'engagement', 'architected', 'managed', 'database', 'using', 'postgresql', 'firebase', 'enhancing', 'data', 'integrity', 'retrieval', 'process', 'implemented', 'responsive', 'solution', 'using', 'react', 'native', 'improving', 'user', 'experience', 'across', 'various', 'device', 'collaborated', 'team', 'deploy', 'application', 'via', 'kubernetes', 'streamlining', 'deployment', 'process', 'enhancing', 'scalability', 'education', 'bachelor', 'degree', 'computer', 'science', 'relevant', 'field', 'university', 'name', 'graduation', 'year', 'united', 'state']"
3,"```markdown\n**Summary** \nDynamic and detail-oriented software developer with a Bachelorâ€™s degree and 1-2 years of experience in building robust web applications. Proficient in various programming languages and frameworks, with a strong focus on efficient code and user experience. Demonstrates excellent problem-solving skills and the ability to work collaboratively in diverse team environments, bringing a proactive approach to development and deployment processes.\n\n**Skills** \n- **Programming Languages:** TypeScript, Java, JavaScript \n- **Databases:** Firebase, MariaDB \n- **Web Frameworks:** React.js, Node.js \n- **Other Frameworks:** React Native, .NET \n- **Tools:** Docker, Ansible \n- **IDEs:** Visual Studio Code, Visual Studio \n- **Operating Systems:** Windows, Linux \n\n**Experience** \n*Software Developer* \n[Your Company Name] â€” Poland \n[Month, Year] to Present \n- Developed and maintained applications utilizing React.js and Node.js, enhancing user interaction and experience. \n- Collaborated with cross-functional teams to design and implement responsive web solutions, ensuring seamless integration with back-end services. \n- Worked extensively with databases like Firebase and MariaDB, optimizing data storage and retrieval processes. \n- Engaged in continuous learning and adoption of best practices in software development, contributing to team knowledge and resourcefulness.\n\n**Education** \n*Bachelorâ€™s Degree in [Your Major]* \n[Your University Name] â€” [Year of Graduation] \n- Completed foundational coursework in computer science, focusing on software development methodologies and modern programming techniques. \n- Participated in various team projects that reinforced collaborative skills and practical application of theoretical knowledge.\n```",female,"```markdown\n**Summary** \nDynamic and detail-oriented software developer with a Bachelorâ€™s degree and 1-2 years of experience in building robust web applications. Proficient in various programming languages and frameworks, with a strong focus on efficient code and user experience. Demonstrates excellent problem-solving skills and the ability to work collaboratively in diverse team environments, bringing a proactive approach to development and deployment processes.\n\n**Skills** \n- **Programming Languages:** TypeScript, Java, JavaScript \n- **Databases:** Firebase, MariaDB \n- **Web Frameworks:** React.js, Node.js \n- **Other Frameworks:** React Native, .NET \n- **Tools:** Docker, Ansible \n- **IDEs:** Visual Studio Code, Visual Studio \n- **Operating Systems:** Windows, Linux \n\n**Experience** \n*Software Developer* \n[Your Company Name] â€” Poland \n[Month, Year] to Present \n- Developed and maintained applications utilizing React.js and Node.js, enhancing user interaction and experience. \n- Collaborated with cross-functional teams to design and implement responsive web solutions, ensuring seamless integration with back-end services. \n- Worked extensively with databases like Firebase and MariaDB, optimizing data storage and retrieval processes. \n- Engaged in continuous learning and adoption of best practices in software development, contributing to team knowledge and resourcefulness.\n\n**Education** \n*Bachelorâ€™s Degree in [Your Major]* \n[Your University Name] â€” [Year of Graduation] \n- Completed foundational coursework in computer science, focusing on software development methodologies and modern programming techniques. \n- Participated in various team projects that reinforced collaborative skills and practical application of theoretical knowledge.\n```","['markdown', 'summary', 'dynamic', 'software', 'developer', 'bachelor', 'degree', 'year', 'experience', 'building', 'robust', 'web', 'application', 'proficient', 'various', 'programming', 'language', 'framework', 'strong', 'focus', 'efficient', 'code', 'user', 'experience', 'demonstrates', 'excellent', 'skill', 'ability', 'work', 'collaboratively', 'diverse', 'team', 'environment', 'bringing', 'proactive', 'approach', 'development', 'deployment', 'process', 'skill', 'programming', 'language', 'typescript', 'java', 'javascript', 'database', 'firebase', 'mariadb', 'web', 'framework', 'framework', 'react', 'native', 'tool', 'docker', 'ansible', 'ides', 'visual', 'studio', 'code', 'visual', 'studio', 'operating', 'system', 'window', 'linux', 'experience', 'software', 'developer', 'company', 'name', 'poland', 'month', 'year', 'present', 'developed', 'maintained', 'application', 'utilizing', 'enhancing', 'user', 'interaction', 'experience', 'collaborated', 'team', 'design', 'implement', 'responsive', 'web', 'solution', 'ensuring', 'seamless', 'integration', 'service', 'worked', 'extensively', 'database', 'like', 'firebase', 'mariadb', 'optimizing', 'data', 'storage', 'retrieval', 'process', 'engaged', 'continuous', 'learning', 'adoption', 'best', 'practice', 'software', 'development', 'contributing', 'team', 'knowledge', 'resourcefulness', 'education', 'bachelor', 'degree', 'major', 'university', 'name', 'year', 'graduation', 'completed', 'foundational', 'coursework', 'computer', 'science', 'focusing', 'software', 'development', 'methodology', 'modern', 'programming', 'technique', 'participated', 'various', 'team', 'project', 'reinforced', 'collaborative', 'skill', 'practical', 'application', 'theoretical', 'knowledge']"

In [9]:
def vectorize_text(tokens, w2v_model):
    # Vectorize the tokens (including bigrams)
    vectors = [w2v_model.wv[word] for word in tokens if word in w2v_model.wv]
    return np.mean(vectors, axis=0) if vectors else np.zeros(w2v_model.vector_size)

In [5]:
# Create bigrams using Gensim's Phrases model
bigram_model = Phrases(job_postings_df['tokens'].tolist() + cvs_df['tokens'].tolist(), min_count=5, threshold=10)

In [6]:
# Apply the bigram model to your tokenized text
bigram_job_postings = [bigram_model[doc] for doc in job_postings_df['tokens']]
bigram_cvs = [bigram_model[doc] for doc in cvs_df['tokens']]

In [7]:
# Train Word2Vec model with CBOW (sg=0) and bigrams
w2v_model_bigrams = Word2Vec(sentences=bigram_job_postings, vector_size=100, window=5, min_count=2, sg=0, workers=4)

# Get the word vectors
word_vectors_bigrams = w2v_model_bigrams.wv

In [10]:
# Vectorize both job postings and CVs using the new bigram model
job_postings_df['vector'] = job_postings_df['tokens'].apply(lambda tokens: vectorize_text(bigram_model[tokens], w2v_model_bigrams))
cvs_df['vector'] = cvs_df['tokens'].apply(lambda tokens: vectorize_text(bigram_model[tokens], w2v_model_bigrams))

In [11]:
# Get the vectors
job_vectors = np.vstack(job_postings_df['vector'])
cv_vectors = np.vstack(cvs_df['vector'])

# Compute cosine similarity between CVs and job postings
similarities = cosine_similarity(cv_vectors, job_vectors)

# Get the top N most similar jobs for each CV
top_n = 10
top_indices = np.argsort(-similarities, axis=1)[:, :top_n]

In [12]:
all_recommendations = []
for cv_idx, job_idxs in tqdm(enumerate(top_indices)):
    for rank, job_idx in enumerate(job_idxs, start=1):  # Start rank from 1
        recs = job_postings_df.iloc[job_idx][['jobPostingId', 'title', 'description', 'gender_category']].copy()
        recs = recs.reset_index(drop=True) 
        recs['rank'] = rank 
        recs['cv_index'] = cv_idx           # Track which CV this is for
        recs['CV'] = cvs_df.iloc[cv_idx]['CV']
        recs['applicant_gender'] = cvs_df.iloc[cv_idx]['gender']
        all_recommendations.append(recs)

16000it [04:35, 58.06it/s]

In [13]:
# Create a DataFrame with the recommendations
recommendations_df = pd.DataFrame(all_recommendations)
recommendations_df = recommendations_df.rename(columns = {0: 'jobPostingId', 1:'title', 2:'description', 3:'gender_category'})
recommendations_df.head()

       jobPostingId                                                     title  \
2335     3823301785                                    React Native Developer
4053     3852604165  Sr. Associate, Software Engineer with Security Clearance
24830    3879772473                                   Staff Software Engineer
21739    3909968109                     Manager, Engineering - Cloud Security
10482    3852303913                                        Frontend Developer

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   description  \
2335                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Cloudpacer is seeking a talented and motivated React Native Developer to join our dynamic team. ð¢ As a React Native Developer, you will play a crucial role in designing, developing, testing, and deploying mobile applications for both Android and iOS platforms. \nResponsibilities:- Collaborate with cross-functional teams to define, design, and ship new features.- Develop and maintain high-quality mobile applications using React Native.- Write clean and efficient code while adhering to best practices in mobile application development.- Troubleshoot, debug, and optimize application performance to ensure a smooth user experience.- Work closely with product managers, designers, and other developers to understand requirements and implement solutions.- Stay updated on the latest trends and technologies in mobile development.\nRequirements:- Bachelor's degree in Computer Science, Software Engineering, or a related field.- 1-2 years of proven experience in developing mobile applications using React Native.- Strong understanding of JavaScript, ES6+, and its nuances.- Familiarity with state management libraries like Redux.- Experience with RESTful APIs and third-party libraries and APIs.- Knowledge of mobile app deployment processes for both App Store and Google Play.- Solid understanding of the full mobile development life cycle.\nPreferred Skills:- Familiarity with native development (Android/iOS).- Experience with continuous integration and deployment.- Ability to work in an agile development environment.- Excellent problem-solving and communication skills.- A proactive attitude towards learning and adopting new technologies.
4053                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Job Title: Sr. Associate, Embedded Software Engineer Job Code: 9357 Job Location: Rochester, NY or Wilmington, MA or Fort Wayne, IN Job Description: L3Harris Space and Airborne Systems is seeking an Embedded Software Engineer for our Rochester, NY or Wilmington, MA locations. As part of a small, passionate, and accomplished team of experts, you will develop software that runs space-based imaging payloads. You will be part of a team responsible for the design, development, and implementation of algorithms, controls, and subsystems for complex aerospace applications. This team is responsible for the complete life cycle of the software you create, from development to testing to operation during a mission. You should be comfortable working in a dynamic team environment, contributing to innovative solutions while demonstrating personal leadership, technical competence, and attention to detail. Our missions support scientific research, national security, and commercial opportunities. We are looking for someone to establish their technical expertise, leadership skills, and innovation to positively impact our mission. Essential Functions: * Develop and lead aspects of the design and implementation of embedded software to support space-based imaging payloads.\n\n Engage in and improve the development cycle of software, from design through deployment and operations. Participate in architecture, design, and code reviews. Collaborate with and lead other engineers to plan and organize the development of our solutions. Participate in all aspects of software development, including design, documentation, testing, and mission integration. Embrace and follow the L3Harris software development process (metrics development, collection, presentation, etc.)\n\nQualifications: * Bachelor's Degree and a minimum of 2 years of software experience. Graduate Degree or equivalent with 0 to 2 years of software experience. In lieu of a degree, minimum of 6 years of software experience.\n\n Experience in space-based payload I&T and ground test equipment development. Hands-on experience, in integrating and testing embedded processing systems to the software/hardware level. Experience in embedded software development using C/C++.\n\nPreferred Additional Skills: * Active Top Secret or TS/SCI clearance or ability to obtain a security clearance.\n\n Developed and deployed embedded software that has been used in real-world space-based imaging application and projects. Experience with DevOps tools including Jira, Bitbucket, Jenkins, and Confluence. Experience in Real-time Operating Systems: VxWorks RTOS, Wind River, Linux, etc. Experience in embedded software development using C. Knowledge of space domain and applications. Experience in estimating large software programs for current and new business opportunities. Experience in developing software for microcontrollers in C/C++ bare metal or with RTOS, working with interfaces such as I2C, SPI, UART, CAN etc. Fundamental knowledge of computer architecture and networks Background in math and physics. In compliance with the Equal Work Act, the salary range for this role is $72,000 - $133,500. This is not a guarantee of compensation or salary, as final offer amount may vary based on factors including but not limited to experience and geographic location. L3Harris also offers a variety of benefits including: health and disability insurance, 401(k) match, flexible spending accounts, EAP, education assistance, parental leave, paid time off, and company-paid holidays. The specific programs and options available to an employee may vary depending on date of hire, schedule type, and the applicability of collective bargaining agreements
24830                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Everbridge is the leading critical event management platform trusted by corporations and communities of all sizes to help keep people safe and businesses running! Connecting more than 100 million people and internet-enabled devices, the company assures that secure, compliant communications are delivered and confirmed, whether locally or globally.\n\nJoin our engineering team and play a vital role in developing and enhancing our flagship CEM platform, focused on providing quality and innovative solutions for our State and Local government customers. Our applications will focus on enabling our users to provide time-critical, life-saving communications to residents and businesses utilizing our risk intelligence, visualization, and alerting platforms.\n\nWhat You'll Do\n\nWork collaboratively with a global team of full-stack developers.Develop using modern web technologies (Java, Python, JavaScript)Develop using modern platform technologies (Kubernetes, Serverless, AWS)Participate in Scrum processesWork across the entire Everbridge platform, implementing new capabilitiesCollaborate across engineering teams and guide adoption of best practices within the teamParticipate in routine maintenance of the system to include software deficiency resolutionWillingness to learn new skills and technologies\n\nWhat You'll Bring\n\n7+ years of experience in full-stack development in a Java or Python full-stack environment.4+ years of experience with front-end development using JavaScript frameworks (e.g. React, Angular)3+ years of experience in a cloud-based deployment environment (e.g. AWS)2+ years experience with containerization (e.g. â Kubernetes, Docker)Experience working with DevOps automation tools (e.g. Jenkins, GitLab CI/CD, salt)Bachelorâs Degree in Computer Engineering, Computer Science, or related fieldsAbility to work independently and remotely while also being able to work closely with team members and collaborate with other teams.\n\nBonus If\n\nExperience working with TypeScriptExperience working in an Agile/Scrum environmentExperience with geospatial technologiesExperience working with public safety projectsSystems experience (e.g. Linux, AWS VPC, IAM, etc.)\n\nWe value our team members and offer an attractive salary package alongside a range of exceptional benefits, including:\n\nComprehensive healthcare coverage to ensure your well-being.Life & Total Permanent Disability Insurance to protect you and your loved ones.Performance-based bonuses.\n\nWe believe in taking care of our team members, personally and professionally, and are dedicated to providing a supportive and rewarding work environment. Join us in our mission to ensure the safety and security of individuals and organizations across the globe.\n\nAbout Everbridge\n\nEverbridge (NASDAQ: EVBG) empowers enterprises and government organizations to anticipate, mitigate, respond to, and recover stronger from critical events. In todayâs unpredictable world, resilient organizations minimize impact to people and operations, absorb stress, and return to productivity faster when deploying critical event management (CEM) technology. Everbridge digitizes organizational resilience by combining intelligent automation with the industryâs most comprehensive risk data to Keep People Safe and Organizations Runningâ¢. For more information, visit www.everbridge.com, read the company blog, and follow on Twitter. Everbridgeâ¦ Empowering Resilience\n\nEverbridge is an Equal Opportunity/Affirmative Action Employer. All qualified Applicants will receive consideration for employment without regard to race, creed, color, religion, or sex including sexual orientation and gender identity, national origin, disability, protected Veteran Status, or any other characteristic protected by applicable federal, state, or local law.\n\n

In [14]:
# recommendations_df = pd.concat(all_recommendations, ignore_index=True)
cols = [ 'cv_index', 'CV', 'applicant_gender', 'jobPostingId', 'title', 'description', 'gender_category', 'rank']
recommendations_df = recommendations_df[cols] 
recommendations_df.head(10)

       cv_index  \
2335          0
4053          0
24830         0
21739         0
10482         0
24840         0
4675          0
36712         0
11450         0
2705          0

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     CV  \
2335   ```plaintext\n**Summary**  \nDynamic and detail-oriented software engineer with 12-14 years of progressive experience in developing robust applications using a variety of programming languages including TypeScript, SQL, and Java. Proven expertise in leveraging web and database technologies such as Node.js, ASP.NET Core, Firebase, and MongoDB. Highly adept in employing modern frameworks and tools to streamline development processes and enhance application performance. Committed to delivering innovative solutions and continuous improvement in the software development lifecycle.\n\n**Skills**  \n- **Programming Languages:** TypeScript, SQL, Java  \n- **Databases:** Firebase, MongoDB  \n- **Web Frameworks:** Node.js, ASP.NET Core  \n- **Other Frameworks:** .NET, Keras  \n- **Tools:** Git, Ansible  \n- **IDEs:** Sublime Text, IntelliJ  \n- **Operating Systems:** Windows, macOS  \n\n**Experience**  \n- Developed and maintained complex software applications, leading projects from conception through deployment.  \n- Collaborated with cross-functional teams to design and implement scalable solutions, enhancing user experience and operational efficiency.  \n- Utilized TypeScript and SQL for backend services and database management, demonstrating fluency in data-driven application development.  \n- Leveraged frameworks such as Node.js and ASP.NET Core to build responsive web applications, driving increased engagement and usability.  \n- Implemented CI/CD practices using Git and Ansible, resulting in improved deployment times and reduced rollout errors.  \n\n**Education**  \nBachelorâ€™s Degree in Computer Science  \n[Your University Name]  \n[Year of Graduation]  \nBrazil  \n```
4053   ```plaintext\n**Summary**  \nDynamic and detail-oriented software engineer with 12-14 years of progressive experience in developing robust applications using a variety of programming languages including TypeScript, SQL, and Java. Proven expertise in leveraging web and database technologies such as Node.js, ASP.NET Core, Firebase, and MongoDB. Highly adept in employing modern frameworks and tools to streamline development processes and enhance application performance. Committed to delivering innovative solutions and continuous improvement in the software development lifecycle.\n\n**Skills**  \n- **Programming Languages:** TypeScript, SQL, Java  \n- **Databases:** Firebase, MongoDB  \n- **Web Frameworks:** Node.js, ASP.NET Core  \n- **Other Frameworks:** .NET, Keras  \n- **Tools:** Git, Ansible  \n- **IDEs:** Sublime Text, IntelliJ  \n- **Operating Systems:** Windows, macOS  \n\n**Experience**  \n- Developed and maintained complex software applications, leading projects from conception through deployment.  \n- Collaborated with cross-functional teams to design and implement scalable solutions, enhancing user experience and operational efficiency.  \n- Utilized TypeScript and SQL for backend services and database management, demonstrating fluency in data-driven application development.  \n- Leveraged frameworks such as Node.js and ASP.NET Core to build responsive web applications, driving increased engagement and usability.  \n- Implemented CI/CD practices using Git and Ansible, resulting in improved deployment times and reduced rollout errors.  \n\n**Education**  \nBachelorâ€™s Degree in Computer Science  \n[Your University Name]  \n[Year of Graduation]  \nBrazil  \n```
24830  ```plaintext\n**Summary**  \nDynamic and detail-oriented software engineer with 12-14 years of progressive experience in developing robust applications using a variety of programming languages including TypeScript, SQL, and Java. Proven expertise in leveraging web and database technologies such as Node.js, ASP.NET Core, Firebase, and MongoDB. Highly adept in employing modern frameworks and tools to streamline development processes and enhance application performance. Committed to delivering innovative solutions and continuous improvement in the software development lifecycle.\n\n**Skills**  \n- **Programming Languages:** TypeScript, SQL, Java  \n- **Databases:** Firebase, MongoDB  \n- **Web Frameworks:** Node.js, ASP.NET Core  \n- **Other Frameworks:** .NET, Keras  \n- **Tools:** Git, Ansible  \n- **IDEs:** Sublime Text, IntelliJ  \n- **Operating Systems:** Windows, macOS  \n\n**Experience**  \n- Developed and maintained complex software applications, leading projects from conception through deployment.  \n- Collaborated with cross-functional teams to design and implement scalable solutions, enhancing user experience and operational efficiency.  \n- Utilized TypeScript and SQL for backend services and database management, demonstrating fluency in data-driven application development.  \n- Leveraged frameworks such as Node.js and ASP.NET Core to build responsive web applications, driving increased engagement and usability.  \n- Implemented CI/CD practices using Git and Ansible, resulting in improved deployment times and reduced rollout errors.  \n\n**Education**  \nBachelorâ€™s Degree in Computer Science  \n[Your University Name]  \n[Year of Graduation]  \nBrazil  \n```
21739  ```plaintext\n**Summary**  \nDynamic and detail-oriented software engineer with 12-14 years of progressive experience in developing robust applications using a variety of programming languages including TypeScript, SQL, and Java. Proven expertise in leveraging web and database technologies such as Node.js, ASP.NET Core, Firebase, and MongoDB. Highly adept in employing modern frameworks and tools to streamline development processes and enhance application performance. Committed to delivering innovative solutions and continuous improvement in the software development lifecycle.\n\n**Skills**  \n- **Programming Languages:** TypeScript, SQL, Java  \n- **Databases:** Firebase, MongoDB  \n- **Web Frameworks:** Node.js, ASP.NET Core  \n- **Other Frameworks:** .NET, Keras  \n- **Tools:** Git, Ansible  \n- **IDEs:** Sublime Text, IntelliJ  \n- **Operating Systems:** Windows, macOS  \n\n**Experience**  \n- Developed and maintained complex software applications, leading projects from conception through deployment.  \n- Collaborated with cross-functional teams to design and implement scalable solutions, enhancing user experience and operational efficiency.  \n- Utilized TypeScript and SQL for backend services and database management, demonstrating fluency in data-driven application development.  \n- Leveraged frameworks such as Node.js and ASP.NET Core to build responsive web applications, driving increased engagement and usability.  \n- Implemented CI/CD practices using Git and Ansible, resulting in improved deployment times and reduced rollout errors.  \n\n**Education**  \nBachelorâ€™s Degree in Computer Science  \n[Your University Name]  \n[Year of Graduation]  \nBrazil  \n```
10482  ```plaintext\n**Summary**  \nDynamic and detail-oriented software engineer with 12-14 years of progressive experience in developing robust applications using a variety of programming languages including TypeScript, SQL, and Java. Proven expertise in leveraging web and database technologies such as Node.js, ASP.NET Core, Firebase, and MongoDB. Highly adept in employing modern frameworks and tools to streamline development processes and enhance application performance. Committed to delivering innovative solutions and continuous improvement in the software development lifecycle.\n\n**Skills**  \n- **Programming Languages:** TypeScript, SQL, Java  \n- **Databases:** Firebase, MongoDB  \n- **Web Frameworks:** Node.js, ASP.NET Core  \n- **Other Frameworks:** .NET, Keras  \n- **Tools:** Git, Ansible  \n- **IDEs:** Sublime Text, IntelliJ  \n- **Operating Systems:** Windows, macOS  \n\n**Experience**  \n- Developed and maintained complex software applications, leading projects from conception through deployment.  \n- Collaborated with cross-functional teams to design and implement scalable solutions, enhancing user experience and operational efficiency.  \n- Utilized TypeScript and SQL for backend services and database management, demonstrating fluency in data-driven application development.  \n- Leveraged frameworks such as Node.js and ASP.NET Core to build responsive web applications, driving increased engagement and usability.  \n- Implemented CI/CD practices using Git and Ansible, resulting in improved deployment times and reduced rollout errors.  \n\n**Education**  \nBachelorâ€™s Degree in Computer Science  \n[Your University Name]  \n[Year of Graduation]  \nBrazil  \n```
24840  ```plaintext\n**Summary**  \nDynamic and detail-oriented software engineer with 12-14 years of progressive experience in developing robust applications using a variety of programming languages including TypeScript, SQL, and Java. Proven expertise in leveraging web and database technologies such as Node.js, ASP.NET Core, Firebase, and MongoDB. Highly adept in employing modern frameworks and tools to streamline development processes and enhance application performance. Committed to delivering innovative solutions and continuous improvement in the software development lifecycle.\n\n**Skills**  \n- **Programming Languages:** TypeScript, SQL, Java  \n- **Databases:** Firebase, MongoDB  \n- **Web Frameworks:** Node.js, ASP.NET Core  \n- **Other Frameworks:** .NET, Keras  \n- **Tools:** Git, Ansible  \n- **IDEs:** Sublime Text, IntelliJ  \n- **Operating Systems:** Windows, macOS  \n\n**Experience**  \n- Developed and maintained complex software applications, leading projects from conception through deployment.  \n- Collaborated with cross-functional teams to design and implement scalable solutions, enhancing user experience and operational efficiency.  \n- Utilized TypeScript and SQL for backend services and database management, demonstrating fluency in data-driven application development.  \n- Leveraged frameworks such as Node.js and ASP.NET Core to build responsive web applications, driving increased engagement and usability.  \n- Implemented CI/CD practices using Git and Ansible, resulting in improved deployment times and reduced rollout errors.  \n\n**Education**  \nBachelorâ€™s Degree in Computer Science  \n[Your University Name]  \n[Year of Graduation]  \nBrazil  \n```
4675   ```plaintext\n**Summary**  \nDynamic and detail-oriented software engineer with 12-14 years of progressive experience in developing robust applications using a variety of programming languages including TypeScript, SQL, and Java. Proven expertise in leveraging web and database technologies such as Node.js, ASP.NET Core, Firebase, and MongoDB. Highly adept in employing modern frameworks and tools to streamline development processes and enhance application performance. Committed to delivering innovative solutions and continuous improvement in the software development lifecycle.\n\n**Skills**  \n- **Programming Languages:** TypeScript, SQL, Java  \n- **Databases:** Firebase, MongoDB  \n- **Web Frameworks:** Node.js, ASP.NET Core  \n- **Other Frameworks:** .NET, Keras  \n- **Tools:** Git, Ansible  \n- **IDEs:** Sublime Text, IntelliJ  \n- **Operating Systems:** Windows, macOS  \n\n**Experience**  \n- Developed and maintained complex software applications, leading projects from conception through deployment.  \n- Collaborated with cross-functional teams to design and implement scalable solutions, enhancing user experience and operational efficiency.  \n- Utilized TypeScript and SQL for backend services and database management, demonstrating fluency in data-driven application development.  \n- Leveraged frameworks such as Node.js and ASP.NET Core to build responsive web applications, driving increased engagement and usability.  \n- Implemented CI/CD practices using Git and Ansible, resulting in improved deployment times and reduced rollout errors.  \n\n**Education**  \nBachelorâ€™s Degree in Computer Science  \n[Your University Name]  \n[Year of Graduation]  \nBrazil  \n```
36712  ```plaintext\n**Summary**  \nDynamic and detail-oriented software engineer with 12-14 years of progressive experience in developing robust applications using a variety of programming languages including TypeScript, SQL, and Java. Proven expertise in leveraging web and database technologies such as Node.js, ASP.NET Core, Firebase, and MongoDB. Highly adept in employing modern frameworks and tools to streamline development processes and enhance application performance. Committed to delivering innovative solutions and continuous improvement in the software development lifecycle.\n\n**Skills**  \n- **Programming Languages:** TypeScript, SQL, Java  \n- **Databases:** Firebase, MongoDB  \n- **Web Frameworks:** Node.js, ASP.NET Core  \n- **Other Frameworks:** .NET, Keras  \n- **Tools:** Git, Ansible  \n- **IDEs:** Sublime Text, IntelliJ  \n- **Operating Systems:** Windows, macOS  \n\n**Experience**  \n- Developed and maintained complex software applications, leading projects from conception through deployment.  \n- Collaborated with cross-functional teams to design and implement scalable solutions, enhancing user experience and operational efficiency.  \n- Utilized TypeScript and SQL for backend services and database management, demonstrating fluency in data-driven application development.  \n- Leveraged frameworks such as Node.js and ASP.NET Core to build responsive web applications, driving increased engagement and usability.  \n- Implemented CI/CD practices using Git and Ansible, resulting in improved deployment times and reduced rollout errors.  \n\n**Education**  \nBachelorâ€™s Degree in Computer Science  \n[Your University Name]  \n[Year of Graduation]  \nBrazil  \n```
11450  ```plaintext\n**Summary**  \nDynamic and detail-oriented software engineer with 12-14 years of progressive experience in developing robust applications using a variety of programming languages including TypeScript, SQL, and Java. Proven expertise in leveraging web and database technologies such as Node.js, ASP.NET Core, Firebase, and MongoDB. Highly adept in employing modern frameworks and tools to streamline development processes and enhance application performance. Committed to delivering innovative solutions and continuous improvement in the software development lifecycle.\n\n**Skills**  \n- **Programming Languages:** TypeScript, SQL, Java  \n- **Databases:** Firebase, MongoDB  \n- **Web Frameworks:** Node.js, ASP.NET Core  \n- **Other Frameworks:** .NET, Keras  \n- **Tools:** Git, Ansible  \n- **IDEs:** Sublime Text, IntelliJ  \n- **Operating Systems:** Windows, macOS  \n\n**Experience**  \n- Developed and maintained complex software applications, leading projects from conception through deployment.  \n- Collaborated with cross-functional teams to design and implement scalable solutions, enhancing user experience and operational efficiency.  \n- Utilized TypeScript and SQL for backend services and database management, demonstrating fluency in data-driven application development.  \n- Leveraged frameworks such as Node.js and ASP.NET Core to build responsive web applications, driving increased engagement and usability.  \n- Implemented CI/CD practices using Git and Ansible, resulting in improved deployment times and reduced rollout errors.  \n\n**Education**  \nBachelorâ€™s Degree in Computer Science  \n[Your University Name]  \n[Year of Graduation]  \nBrazil  \n```
2705   ```plaintext\n**Summary**  \nDynamic and detail-oriented software engineer with 12-14 years of progressive experience in developing robust applications using a variety of programming languages including TypeScript, SQL, and Java. Proven expertise in leveraging web and database technologies such as Node.js, ASP.NET Core, Firebase, and MongoDB. Highly adept in employing modern frameworks and tools to streamline development processes and enhance application performance. Committed to delivering innovative solutions and continuous improvement in the software development lifecycle.\n\n**Skills**  \n- **Programming Languages:** TypeScript, SQL, Java  \n- **Databases:** Firebase, MongoDB  \n- **Web Frameworks:** Node.js, ASP.NET Core  \n- **Other Frameworks:** .NET, Keras  \n- **Tools:** Git, Ansible  \n- **IDEs:** Sublime Text, IntelliJ  \n- **Operating Systems:** Windows, macOS  \n\n**Experience**  \n- Developed and maintained complex software applications, leading projects from conception through deployment.  \n- Collaborated with cross-functional teams to design and implement scalable solutions, enhancing user experience and operational efficiency.  \n- Utilized TypeScript and SQL for backend services and database management, demonstrating fluency in data-driven application development.  \n- Leveraged frameworks such as Node.js and ASP.NET Core to build responsive web applications, driving increased engagement and usability.  \n- Implemented CI/CD practices using Git and Ansible, resulting in improved deployment times and reduced rollout errors.  \n\n**Education**  \nBachelorâ€™s Degree in Computer Science  \n[Your University Name]  \n[Year of Graduation]  \nBrazil  \n```

      applicant_gender  jobPostingId  \
2335            female    3823301785
4053            female    3852604165
24830           female    3879772473
21739           female    3909968109
10482           female    3852303913
24840           female    3879769905
4675            female    3880218165
36712           female    3995053255
11450           female    3909641661
2705            female    3824234149

                                                          title  \
2335                                     React Native Developer
4053   Sr. Associate, Software Engineer with Security Clearance
24830                                   Staff Software Engineer
21739                     Manager, Engineering - Cloud Security
10482                                        Frontend Developer
24840                               Senior Software Engineer II
4675                                Senior Software Engineer II
36712                              VR Engine Architect - UbiSim
11450                                  Senior Flutter Developer

In [15]:
recommendations_df.to_csv(f'Recommendation Data/word2vec_cbow_bigrams_{len(recommendations_df)}.csv', index=False)